import { ConfigProvider } from "antd";
import Header from "../Layout/Header";
import "../styles/main.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <ConfigProvider
          theme={{
            token: {
              // Seed Token
              colorPrimary: "#7950f2",
              borderRadius: 4,
              colorBorder: "#b197fc",
              // Alias Token
              // colorBgContainer: "aliceblue",
            },
          }}
        >
          <Header />
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
