FROM node:21.6 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM node:21.6-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
# TypeScript 실행 파일은 필요 없음
RUN npm install --omit=dev

EXPOSE 8080
# 프로덕션 환경에서는 빌드된 JavaScript 파일 실행
CMD ["node", "dist/index.js"]