FROM nginx:1.25-alpine

# 기본 설정 파일 제거
RUN rm /etc/nginx/conf.d/default.conf

# SSL 디렉토리 생성
RUN mkdir -p /etc/nginx/ssl

# 보안 강화 설정
RUN sed -i 's/# server_tokens off/server_tokens off/' /etc/nginx/nginx.conf

# 사용자 설정 복사
COPY nginx.conf /etc/nginx/conf.d/

# HTTP와 HTTPS 포트 노출
EXPOSE 80
EXPOSE 443

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]