name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main # 또는 master, 메인 브랜치 이름에 맞게 조정
      - ",/"
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECS_CLUSTER: photo-look-cluster

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Frontend 체크 및 배포
      - name: Check frontend image
        id: check-frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: photo-look-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # 현재 ECS에 배포된 프론트엔드 서비스의 태스크 정의 가져오기
          CURRENT_TASK_DEF=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services photo-look-frontend-service --query 'services[0].taskDefinition' --output text)
          if [ "$CURRENT_TASK_DEF" != "None" ]; then
            # 태스크 정의로부터 현재 이미지 URI 가져오기
            CURRENT_IMAGE=$(aws ecs describe-task-definition --task-definition $CURRENT_TASK_DEF --query 'taskDefinition.containerDefinitions[0].image' --output text)
            NEW_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "::set-output name=current_image::$CURRENT_IMAGE"
            echo "::set-output name=new_image::$NEW_IMAGE"
            
            # 이전에 배포된 이미지의 SHA 태그 추출
            CURRENT_SHA=$(echo $CURRENT_IMAGE | sed -e 's/.*://')
            
            # 만약 현재 SHA와 새 SHA가 동일하다면 이미 배포된 것으로 간주
            if [ "$CURRENT_SHA" == "$IMAGE_TAG" ]; then
              echo "Frontend image with SHA $IMAGE_TAG already deployed. Skipping frontend deployment."
              echo "::set-output name=skip::true"
            else
              echo "Frontend image needs to be updated. Proceeding with deployment."
              echo "::set-output name=skip::false"
            fi
          else
            echo "No current frontend service found. Proceeding with deployment."
            echo "::set-output name=skip::false"
          fi

      # Frontend 컨테이너 빌드 및 배포 (필요한 경우에만)
      - name: Build, tag, and push frontend image
        id: build-frontend
        if: steps.check-frontend.outputs.skip != 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: photo-look-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f frontend/Dockerfile ./frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "frontend_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in frontend task definition
        id: frontend-task-def
        if: steps.check-frontend.outputs.skip != 'true'
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: frontend/frontend-task-definition.json
          container-name: frontend-container
          image: ${{ steps.build-frontend.outputs.frontend_image }}

      - name: Deploy frontend to Amazon ECS
        if: steps.check-frontend.outputs.skip != 'true'
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.frontend-task-def.outputs.task-definition }}
          service: photo-look-frontend-service
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      # Server 체크 및 배포
      - name: Check server image
        id: check-server
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: photo-look-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # 현재 ECS에 배포된 백엔드 서비스의 태스크 정의 가져오기
          CURRENT_TASK_DEF=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services photo-look-backend-service --query 'services[0].taskDefinition' --output text)
          if [ "$CURRENT_TASK_DEF" != "None" ]; then
            # 태스크 정의로부터 현재 이미지 URI 가져오기
            CURRENT_IMAGE=$(aws ecs describe-task-definition --task-definition $CURRENT_TASK_DEF --query 'taskDefinition.containerDefinitions[0].image' --output text)
            NEW_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "::set-output name=current_image::$CURRENT_IMAGE"
            echo "::set-output name=new_image::$NEW_IMAGE"
            
            # 이전에 배포된 이미지의 SHA 태그 추출
            CURRENT_SHA=$(echo $CURRENT_IMAGE | sed -e 's/.*://')
            
            # 만약 현재 SHA와 새 SHA가 동일하다면 이미 배포된 것으로 간주
            if [ "$CURRENT_SHA" == "$IMAGE_TAG" ]; then
              echo "Server image with SHA $IMAGE_TAG already deployed. Skipping server deployment."
              echo "::set-output name=skip::true"
            else
              echo "Server image needs to be updated. Proceeding with deployment."
              echo "::set-output name=skip::false"
            fi
          else
            echo "No current server service found. Proceeding with deployment."
            echo "::set-output name=skip::false"
          fi

      # Server 컨테이너 빌드 및 배포 (필요한 경우에만)
      - name: Build, tag, and push server image
        id: build-server
        if: steps.check-server.outputs.skip != 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: photo-look-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f server/Dockerfile ./server
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "server_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in server task definition
        id: server-task-def
        if: steps.check-server.outputs.skip != 'true'
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: server/backend-task-definition.json
          container-name: backend-containe
          image: ${{ steps.build-server.outputs.server_image }}

      - name: Deploy server to Amazon ECS
        if: steps.check-server.outputs.skip != 'true'
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.server-task-def.outputs.task-definition }}
          service: photo-look-backend-service
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      # Flask 체크 및 배포
      - name: Check flask image
        id: check-flask
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: photo-look-flask
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # 현재 ECS에 배포된 flask 서비스의 태스크 정의 가져오기
          CURRENT_TASK_DEF=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services photo-look-flask-service --query 'services[0].taskDefinition' --output text)
          if [ "$CURRENT_TASK_DEF" != "None" ]; then
            # 태스크 정의로부터 현재 이미지 URI 가져오기
            CURRENT_IMAGE=$(aws ecs describe-task-definition --task-definition $CURRENT_TASK_DEF --query 'taskDefinition.containerDefinitions[0].image' --output text)
            NEW_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "::set-output name=current_image::$CURRENT_IMAGE"
            echo "::set-output name=new_image::$NEW_IMAGE"
            
            # 이전에 배포된 이미지의 SHA 태그 추출
            CURRENT_SHA=$(echo $CURRENT_IMAGE | sed -e 's/.*://')
            
            # 만약 현재 SHA와 새 SHA가 동일하다면 이미 배포된 것으로 간주
            if [ "$CURRENT_SHA" == "$IMAGE_TAG" ]; then
              echo "Flask image with SHA $IMAGE_TAG already deployed. Skipping flask deployment."
              echo "::set-output name=skip::true"
            else
              echo "Flask image needs to be updated. Proceeding with deployment."
              echo "::set-output name=skip::false"
            fi
          else
            echo "No current flask service found. Proceeding with deployment."
            echo "::set-output name=skip::false"
          fi

      # Flask 컨테이너 빌드 및 배포 (필요한 경우에만)
      - name: Build, tag, and push flask image
        id: build-flask
        if: steps.check-flask.outputs.skip != 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: photo-look-flask
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f flask/Dockerfile ./flask
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "flask_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in flask task definition
        id: flask-task-def
        if: steps.check-flask.outputs.skip != 'true'
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: flask/flask-task-definition.json
          container-name: flask-container
          image: ${{ steps.build-flask.outputs.flask_image }}

      - name: Deploy flask to Amazon ECS
        if: steps.check-flask.outputs.skip != 'true'
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.flask-task-def.outputs.task-definition }}
          service: photo-look-flask-service
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
